"""OpenClaw lifecycle-state helpers."""

from .adapter import (
    ChannelLookupPacketError,
    ChannelLookupResolution,
    resolve_channel_lookup_packet,
)
from .commands import (
    LifecycleCommand,
    LifecycleCommandError,
    MapProjectHereCommand,
    MigrateStateHereCommand,
    PinLifecycleStatusCommand,
    ProjectMappingCommand,
    ProjectMigrationCommand,
    ProjectionCommand,
    StateSetCommand,
    StateStatusCommand,
    parse_lifecycle_command,
    parse_map_project_here_command,
    parse_migrate_state_here_command,
    parse_pin_lifecycle_status_command,
    parse_state_set_command,
    parse_state_status_command,
)
from .context import (
    ChannelContextError,
    CurrentChannelContext,
    resolve_current_channel_context,
)
from .discord_response import (
    LifecycleResponseError,
    format_lifecycle_command_error,
    format_state_status_response,
    format_state_write_confirmation,
)
from .discord_runtime import (
    DiscordRuntimeAdapterError,
    DiscordRuntimeOptions,
    handle_discord_pin_lifecycle_status_command,
    handle_discord_state_command,
    normalize_channel_lookup_response,
)
from .mapping import (
    ProjectMappingError,
    SafeProjectMapping,
    resolve_safe_project_mapping,
)
from .pinned_status import (
    MANAGED_FOOTER,
    ManagedDiscordMessage,
    PinnedStatusApplyCallables,
    PinnedStatusProjectionError,
    PinnedStatusProjectionOptions,
    format_pinned_status_message,
    format_pinned_status_projection_response,
    handle_pinned_status_projection,
    plan_pinned_status_projection,
)
from .project_state import (
    MappedProjectStateError,
    MappedProjectWriteOptions,
    read_mapped_project_lifecycle_state,
    write_mapped_project_lifecycle_state,
)
from .project_mapping import (
    MapProjectHereError,
    MapProjectHereOptions,
    format_map_project_here_response,
    map_project_here,
)
from .registry_state import (
    ChannelRegistryStateError,
    ChannelRegistryWriteOptions,
    read_channel_registry_lifecycle_state,
    write_channel_registry_lifecycle_state,
)
from .status import read_lifecycle_state
from .state import (
    ALLOWED_STATES,
    LifecycleStateError,
    allowed_states_text,
    is_valid_state,
    validate_state,
)
from .state_migration import (
    StateMigrationError,
    StateMigrationOptions,
    format_state_migration_response,
    migrate_registry_state_to_project,
)
from .workflow import (
    LifecycleWorkflowError,
    LifecycleWorkflowOptions,
    handle_lifecycle_command,
)

__all__ = [
    "ALLOWED_STATES",
    "ChannelContextError",
    "ChannelLookupPacketError",
    "ChannelLookupResolution",
    "ChannelRegistryStateError",
    "ChannelRegistryWriteOptions",
    "CurrentChannelContext",
    "DiscordRuntimeAdapterError",
    "DiscordRuntimeOptions",
    "LifecycleCommand",
    "LifecycleCommandError",
    "LifecycleResponseError",
    "LifecycleStateError",
    "LifecycleWorkflowError",
    "LifecycleWorkflowOptions",
    "MapProjectHereCommand",
    "MapProjectHereError",
    "MapProjectHereOptions",
    "MappedProjectStateError",
    "MappedProjectWriteOptions",
    "MigrateStateHereCommand",
    "MANAGED_FOOTER",
    "ManagedDiscordMessage",
    "PinLifecycleStatusCommand",
    "PinnedStatusApplyCallables",
    "PinnedStatusProjectionError",
    "PinnedStatusProjectionOptions",
    "ProjectMappingError",
    "ProjectMappingCommand",
    "ProjectMigrationCommand",
    "ProjectionCommand",
    "SafeProjectMapping",
    "StateSetCommand",
    "StateStatusCommand",
    "StateMigrationError",
    "StateMigrationOptions",
    "allowed_states_text",
    "format_lifecycle_command_error",
    "format_map_project_here_response",
    "format_pinned_status_message",
    "format_pinned_status_projection_response",
    "format_state_migration_response",
    "format_state_status_response",
    "format_state_write_confirmation",
    "handle_discord_state_command",
    "handle_discord_pin_lifecycle_status_command",
    "handle_lifecycle_command",
    "handle_pinned_status_projection",
    "is_valid_state",
    "map_project_here",
    "migrate_registry_state_to_project",
    "parse_lifecycle_command",
    "parse_map_project_here_command",
    "parse_migrate_state_here_command",
    "parse_pin_lifecycle_status_command",
    "parse_state_set_command",
    "parse_state_status_command",
    "read_channel_registry_lifecycle_state",
    "read_lifecycle_state",
    "read_mapped_project_lifecycle_state",
    "normalize_channel_lookup_response",
    "plan_pinned_status_projection",
    "resolve_channel_lookup_packet",
    "resolve_current_channel_context",
    "resolve_safe_project_mapping",
    "validate_state",
    "write_channel_registry_lifecycle_state",
    "write_mapped_project_lifecycle_state",
]
